(1258702, 100, 2)
(1292542, 100, 2)

In [15]:
import numpy as np
import scipy
from scipy import stats

array1 = np.random.rand(6, 4, 2)
array2 = np.random.rand(6, 4, 2)

In [16]:
array1.shape

(6, 4, 2)

In [17]:
dataset = [array1, array2]
print(len(dataset))
print(len(dataset[0]))


2
6


In [18]:
global num_features
num_features = 2

def extract_features(extracted_data, chunk_size = dataset[0].shape[1]):
    freq = 100 # Data frequency of 200HZ
    num_chunks = extracted_data.shape[0]//chunk_size
    num_sensors = extracted_data.shape[2]
    features = np.zeros((num_chunks, num_features*num_sensors))
    
    positive = 0
    negative = 0
    
    
    for i in range(num_chunks):
        chunk = extracted_data[i*chunk_size:(i+1)*chunk_size, :, :]

        fft_sum_list = []
        fft_sum_list_1 = []

        fft_vals = np.fft.fft(chunk[i,])
        print(f'fft_vals {fft_vals}')



        for j in range(num_sensors):                
            fft_vals_1 = np.fft.fft(chunk[j,])
            #print(fft_vals_1)
            fft_sum_1 = np.sum(np.abs(fft_vals_1))/freq

            fft_sum_list_1.append(fft_sum_1)




        positive_count = np.count_nonzero(fft_vals_1 > 0)
        negative_count = np.count_nonzero(fft_vals_1 < 0)
        positive += positive_count
        negative += negative_count
        print("Number of positive values:", positive_count)
        print("Number of negative values:", negative_count)


        fft_sum_list = np.array(fft_sum_list)

        features[i,:] = np.concatenate([fft_sum_list])
        global feature_names
        feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
            'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    print(f'total positive values for position {positive}')
    print(f'total negative values for position {negative}')        
    return features


In [19]:
chunk_size = 100
array4 = np.random.rand(200, 100, 2)
num_chunks = array4.shape[0]//chunk_size
print(num_chunks)

2


In [20]:
for i in range (len(dataset)):
    print(len(dataset[i]))
    for j in range(len(dataset[i])):
        #mean = np.mean(dataset[i][j], axis=(0, 1))
        for k in range(dataset[i].shape[2]):
        #    print(dataset[j][k])
        #    print('\n')
        
        
            mean = np.mean(dataset[i][j])

6
6


In [21]:
print(len(dataset))

2


In [22]:
print(dataset[0][0][0])

[0.52516791 0.02581056]


In [108]:
array5 = np.random.rand(4, 3, 2)
print(array5)
mean_array = np.mean(array5, axis=1)
print("mean")
print(mean_array)

[[[0.34057233 0.40787101]
  [0.0330145  0.95078993]
  [0.93006847 0.34408808]]

 [[0.43865505 0.37873204]
  [0.73649542 0.86550904]
  [0.58649143 0.41571336]]

 [[0.87849194 0.19232665]
  [0.09425554 0.02415723]
  [0.04927493 0.09519305]]

 [[0.76809959 0.68029813]
  [0.22427172 0.15028906]
  [0.69013314 0.33326894]]]
mean
[[0.43455177 0.56758301]
 [0.58721397 0.55331815]
 [0.34067414 0.10389231]
 [0.56083482 0.38795204]]


In [24]:
print(mean_array[0])
print(mean_array[1])

0.41570530128982497
0.5845603026035247


In [45]:
array5 = np.random.rand(4, 3, 2)
array5.shape

(4, 3, 2)

In [52]:
global num_features
num_features = 12
def feature_extraction(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
    
    #mean_sensor_1 = mean_array[:,0]
    #mean_sensor_2 = mean_array[:,1]
    #median_sensor_1 = median_array[:,0]
    #median_sensor_2 = median_array[:,1]
    #std_sensor_1 = std_array[:,0]
    #std_sensor_2 = std_array[:,1]
    #min_sensor_1 = min_val_array[:,0]
    #min_sensor_2 = min_val_array[:,1]
    #max_sensor_1 = max_val_array[:,0]
    #max_sensor_2 = max_val_array[:,1]
    #sum_sensor_1 = sum_val_array[:,0]
    #sum_sensor_2 = sum_val_array[:,1]
    #print(mean_sensor_1)
    #print(sum_sensor_2)
    #print(mean_sensor_1.shape)
    #print(sum_sensor_2.shape)
    
    features = np.zeros((len(data), num_features*2))
    
    #for i in range(num_features):
    #    features[i,:] = np.concatenate([mean_sensor_1, mean_sensor_2, median_sensor_1, median_sensor_2, std_sensor_1, std_sensor_2,\
    #        min_sensor_1, min_sensor_2, max_sensor_1, max_sensor_2, sum_sensor_1, sum_sensor_2])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    
        
    #print(mean_sensor_2)
    #print(mean_array)

In [53]:
x = feature_extraction(array5)
print(x)
#np.mean(array5[0], axis=0)

[0.5524484  0.60466399 0.82602587 0.21441144]
[0.01285484 0.01659482 0.01896654 0.02109403]
(4,)
(4,)
None


In [ ]:
feature_extraction(array5)

In [ ]:
array7 = np.random.rand(20, 10, 2)

#fft_vals = np.fft.fft(chunk[i,])
#print(f'fft_vals {fft_vals}')

for i in range(len(array7)):
        fft_vals = np.fft.fft(array7[i])
        print(fft_vals)
        
        positive_count = np.count_nonzero(fft_vals > 0)
        negative_count = np.count_nonzero(fft_vals < 0)
        print(positive_count)
        print(negative_count)
        
        


In [ ]:
array8 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
fft_vals = np.fft.fft(array8)
print(fft_vals)

In [ ]:
array9 = np.random.rand(10, 10)
print(array9, end = '\n\n')
fft_vals = np.fft.fft(array9)
print(fft_vals, end = '\n\n')

for i in range(len(array9[0])):
    fft_vals2 = np.fft.fft(array9[0])
    
print(fft_vals2, end = '\n\n')

fft_vals3 = np.fft.fft(array9[0])

print(fft_vals3)                      
                       

In [ ]:
array10 = [[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16]]

print(np.fft.fft(array10[0]))

In [ ]:
array11 = np.random.rand(4, 4)
#print(array11, end = '\n\n')
fft_vals = np.fft.fft(array11)
print(fft_vals, end = '\n\n')
#print(fft_vals, end = '\n\n')

positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(positive_count)
print(negative_count)



array12 = np.random.rand(8, 8, 2)
#print(array12)

'''
for i in range(len(array12[0])):
    print(f'Shape of the array: {array12[i].shape}')
    fft_vals = np.fft.fft(array12[0])
    print(fft_vals)
'''
#fft_val = np.fft.fft(array11[0])
#array11 = np.arange(2,2,2)
for i in range(len(array12[0])):
    print(f'Shape of the array: {array12[i].shape}')
    fft_vals = np.fft.fft(array12[0])
    print(fft_vals)


In [ ]:
array13 = np.random.rand(1000)

fft_vals = np.fft.fft(array13)
print(fft_vals)



positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(positive_count)
print(negative_count)

In [ ]:
array14 = np.random.rand(10,10,10)

for i in range(len(array14[0])):
    for j in range(len(array14[1])):
        print(array14[0][1].shape)
        fft_vals = np.fft.fft(array14[0][1])
        
#print(fft_vals[0][0], end = '\n\n')
print(fft_vals)
positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(f'number of positive fft values: {positive_count}')
print(f'number of negative fft values: {negative_count}', end = '\n\n')

print(fft_vals[0], end = '\n\n\n')




In [ ]:
i = 0
j = 0
k = 0
for i in range(len(array14[i])):
    for j in range(len(array14[j])):
        for k in range(len(array14[k])):
            fft_vals = np.fft.fft(array14)
            

print(fft_vals[0][0])

fft_vals2 = np.fft.fft(array14)
print(fft_vals2[0][0])


print(array14.shape)

In [ ]:
import matplotlib.pyplot as plt
t = np.arange(256)
sp = np.fft.fft(np.sin(t))
freq = np.fft.fftfreq(t.shape[-1])
plt.plot(freq, sp.real, freq, sp.imag)
plt.show()

In [ ]:
i = 0
j = 0
k = 0
array14 = np.random.rand(10,10,10)
for i in range(len(array14[i])):
    for j in range(len(array14[j])):
        for k in range(len(array14[k])):
            fft_vals = np.fft.fft(array14)
            

print(fft_vals[0][0])

fft_vals2 = np.fft.fft(array14)
print(fft_vals2[0][0])


print(array14.shape)

In [ ]:
array15 = np.random.rand(3,3,3)
fft_vals = np.fft.fftn(array15)
print(fft_vals)

In [ ]:
fft_vals = np.fft.fftn(array15)
print(fft_vals, end = '\n\n')
fft_vals2 = np.fft.fftn(np.sin(array15))
print(fft_vals2)

In [ ]:
arr = [2,4,6,8,10,12,14,16,18,20]
arr2 = [[2,4,6,8,10],[12,14,16,18,20]]

arr = np.array(arr)
arr2 = np.array(arr2)

print(arr.shape)
print(arr2.shape)



In [ ]:
fft_vals = np.fft.fft(arr)
fft_vals2 = np.fft.fftn(arr2)

In [ ]:
print(fft_vals, end = '\n'*3)
print(fft_vals2)

In [ ]:
arr3 = np.random.rand(4,3,2)
mean_array = np.empty((len(arr3),2), dtype = float)
fft_vals = np.empty((len(arr3),2), dtype = float)
#print(len(arr3[2]))
arr3[0].shape
i=0
j=0

for i in range(len(arr3)):
        mean_array[i] = np.mean(arr3[i], axis=0)
        for j in range(len(arr3[1])):
                pass
                #print(arr3[i][j])
                #print(arr3[i][j].shape)
                #fft_vals[i]
flat_arr = arr3.reshape(len(arr3)*len(arr3[1]), len(arr3[0][1]))
print(flat_arr)
             
#print('\n'*3)
#print(arr3)

k = 0
for k in range(len(arr3[1])):
        chunk = flat_arr[k * len(arr3[1]) : (k + 1) * len(arr3[1]), ]
        
        #print(chunk, end = '\n'*4)
        sensor_1 = chunk[:,0]
        sensor_2 = chunk[:,1]
        #sp = np.fft.fft(np.sin(chunk))
        print(sensor_1)
        print(sensor_2)
#print(mean_array)

#print('\n'*3)


#print(fft_vals)

In [ ]:
arr3 = np.random.rand(4,3,2)
print(len(arr3))
print(len(arr3[1]))
print(len(arr3[0][1]))
print(len(arr3[2]))
print(len(arr3[3]))



In [ ]:
import numpy as np

# Create a Numpy array with shape (4,2,2)
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]])

# Flatten the array to shape (8,2)
flat_arr = arr.reshape(8, 2)
print(flat_arr)

In [ ]:
t = np.linspace(0, 1, 1000)
print(t)

In [ ]:
import matplotlib.pyplot as plt
t = np.arange(256)
sp = np.fft.fft(np.sin(t))
freq = np.fft.fftfreq(t.shape[-1])
plt.plot(freq, sp.real, freq, sp.imag)
plt.show()

In [ ]:
arr3 = np.random.rand(4,3,2)
mean_array = np.empty((len(arr3),2), dtype = float)
fft_vals = np.empty((len(arr3),2), dtype = float)
fft_sums = np.empty((len(arr3),2), dtype = float)

#print(len(arr3[2]))
arr3[0].shape
i=0
j=0

for i in range(len(arr3)):
        mean_array[i] = np.mean(arr3[i], axis=0)
        for j in range(len(arr3[1])):
                pass
                #print(arr3[i][j])
                #print(arr3[i][j].shape)
                #fft_vals[i]
flat_arr = arr3.reshape(len(arr3)*len(arr3[1]), len(arr3[0][1]))
print(flat_arr)
             
#print('\n'*3)
#print(arr3)

k = 0
for k in range(len(arr3[1])):
        chunk = flat_arr[k * len(arr3[1]) : (k + 1) * len(arr3[1]), ]
        
        #print(chunk, end = '\n'*4)
        sensor_1 = chunk[:,0]
        sensor_2 = chunk[:,1]
        
        
        sp1 = np.fft.fft(np.sin(sensor_1))
        ps1 = np.abs(sp1)**2
        sp2 = np.fft.fft(np.sin(sensor_2))
        ps2 = np.abs(sp2)**2
        #sp = np.fft.fft(np.sin(chunk))

        print(sp1)
        print(sensor_1)
        print(sensor_2)
#print(mean_array)

#print('\n'*3)


#print(fft_vals)

In [18]:
import numpy as np
from scipy.integrate import trapz
from scipy.fft import fft

arr3 = np.random.rand(7,6,2)
mean_array = np.empty((len(arr3),2), dtype = float)
fft_vals = np.empty((len(arr3),2), dtype = float)
fft_sums = np.empty((len(arr3),2), dtype = float)
freq = 100
arr3[0].shape

flat_arr = arr3.reshape(len(arr3)*len(arr3[1]), len(arr3[0][1]))
print(flat_arr)

k = 0
for k in range(len(arr3[1])):
        mean_array[k] = np.mean(arr3[k], axis=0)
        chunk = flat_arr[k * len(arr3[1]) : (k + 1) * len(arr3[1]), ]
        
        sensor_1 = chunk[:,0]
        sensor_2 = chunk[:,1]
        
        
        sp1 = np.fft.fft(np.sin(sensor_1))
        ps1 = np.abs(sp1)**2
        sp2 = np.fft.fft(np.sin(sensor_2))
        ps2 = np.abs(sp2)**2
        

        print(sp1)
        print(sensor_1.shape)
        print(sensor_2.shape)
        
        
                # Define the frequency range of interest
        sensor_1_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx1 = np.logical_and(sensor_1_freq >= 0, sensor_1_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area1 = trapz(ps1[idx1], sensor_1_freq[idx1])


        # Define the frequency range of interest
        sensor_2_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx2 = np.logical_and(sensor_2_freq >= 0, sensor_2_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area2 = trapz(ps2[idx1], sensor_2_freq[idx1])


        fft_sums[k] = [area1, area2]

        print(f"Area under the curve: {area1:.2f}")
        print(f"Area under the curve: {area2:.2f}")
        
        
        max_ps1 = np.max(sp1)
        max_ps2 = np.max(sp2)
        
            
        argmax_ind_1 = np.arange(len(sp1))
        print(argmax_ind_1)
        argmax_list_1 = argmax_ind_1[np.argsort(-np.abs(sp1))]
        
        #for x in argmax_list:
        #        if x * freq
        max_power_frequency_1 = argmax_list_1[0] * (freq / len(chunk))
        
        
        
        argmax_ind_2 = np.arange(len(sp2))
        print(argmax_ind_2)
        argmax_list_2 = argmax_ind_2[np.argsort(-np.abs(sp2))]
        
        #for x in argmax_list:
        #        if x * freq
        max_power_frequency_2 = argmax_list_2[0] * (freq / len(chunk))
        
        
        
        
        print(len(chunk))
                
print('wartosc argmax')
print(argmax_list)
        
#print(mean_array)

#print('\n'*3)

print(fft_sums)
#print(fft_vals)
print(mean_array)

[[0.41730973 0.55492121]
 [0.23606062 0.53366394]
 [0.95614295 0.66525499]
 [0.67879027 0.5097972 ]
 [0.98684739 0.57324366]
 [0.04713546 0.84845119]
 [0.29517165 0.52628917]
 [0.61376105 0.93674979]
 [0.09737312 0.79858908]
 [0.57242978 0.62834791]
 [0.06366835 0.85382152]
 [0.41645854 0.96833787]
 [0.65128996 0.17101733]
 [0.58945619 0.76398031]
 [0.20826831 0.71041669]
 [0.23263712 0.86629674]
 [0.23778187 0.1005289 ]
 [0.94641065 0.11468968]
 [0.06657001 0.70719489]
 [0.29359977 0.96781641]
 [0.19323738 0.6632768 ]
 [0.17744883 0.46773101]
 [0.38501419 0.79929466]
 [0.2169348  0.74744521]
 [0.86937445 0.33872961]
 [0.74195556 0.64953144]
 [0.7757101  0.8876109 ]
 [0.34782047 0.04330595]
 [0.79678366 0.42622825]
 [0.80823031 0.45791565]
 [0.05743465 0.49196271]
 [0.73165848 0.13235555]
 [0.51434742 0.67337818]
 [0.22142576 0.41477166]
 [0.44056111 0.01477542]
 [0.78357675 0.66516089]
 [0.62574908 0.81718535]
 [0.95182652 0.14945727]
 [0.96957877 0.25179588]
 [0.53344423 0.89320306]


In [9]:
a = np.array([1, 2, 3, 4])
print(a.shape)
a_reshaped = a.reshape(-1,len(a))
print(a_reshaped.shape)
print(a)
print(a_reshaped)
b = np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

(4,)
(1, 4)
[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [145]:
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0, 12, 18 , 2])
print(a)
max = np.max(a)


ind = np.argpartition(a, max)#[-4:]
print(ind)
for x in ind:
    print(a[x])

[ 9  4  4  3  3  9  0  4  6  0 12 18  2]


ValueError: kth(=18) out of bounds (13)

In [130]:
global num_features
num_features = 12
def feature_extraction(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    kurtosis_array = np.empty((len(data),2), dtype = float)
    skewness_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
        kurtosis_array[i] = scipy.stats.kurtosis(data[i], axis=0)
        skewness_array[i] = scipy.stats.skew(data[i], axis=0)
        
    print(mean_array.shape)
    #features = np.zeros((len(data), num_features))
    #print(features.shape)
    #for i in range(num_features):
    #    features[i,:] = np.concatenate([mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    features = np.concatenate((mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array, kurtosis_array, skewness_array), axis = 1)
    return features    
    #print(mean_sensor_2)
    #print(mean_array)

In [131]:
array5 = np.random.rand(4, 2, 2)
array5.shape



(4, 2, 2)

In [132]:
feature_extraction(array5)
a = feature_extraction(array5)
a.shape

(4, 2)
(4, 2)


(4, 16)

In [122]:
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]])
#print(arr.shape)
print(arr)
mean_array = np.mean(arr, axis=0)
print(mean_array, end = '\n'*3)
mean_array = np.mean(arr, axis=1)
print(mean_array, end = '\n'*3)
kurtosis  = scipy.stats.kurtosis(arr, axis=1)
print(np.mean(arr, axis=2))


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[ 7.  8.]
 [ 9. 10.]]


[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


[[ 1.5  3.5]
 [ 5.5  7.5]
 [ 9.5 11.5]
 [13.5 15.5]]


In [94]:
print(array5)

[[[0.17335316 0.53124399]
  [0.47219582 0.94296123]]

 [[0.88490254 0.49953869]
  [0.00793515 0.33842255]]

 [[0.64285805 0.90941906]
  [0.86520882 0.2582693 ]]

 [[0.69616418 0.54533699]
  [0.37404124 0.42902284]]]


In [115]:
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]])
kurtosis  = scipy.stats.kurtosis(arr, axis=1)
print(kurtosis)


[[-2. -2.]
 [-2. -2.]
 [-2. -2.]
 [-2. -2.]]


In [129]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
#print(arr.shape)
print(arr)
mean_array = np.mean(arr, axis=0)
print(mean_array, end = '\n'*3)
mean_array = np.mean(arr, axis=1)
print(mean_array, end = '\n'*3)
kurtosis  = scipy.stats.kurtosis(arr, axis=0)
print(kurtosis)
#print(np.mean(arr, axis=2))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 7.  8.  9. 10.]


[ 2.5  6.5 10.5 14.5]


[-1.36 -1.36 -1.36 -1.36]


In [148]:
a = np.array([9, 4, 4, 3, 3, 9, 0, 4, 6, 0, 12, 18 , 2])
b = np.argsort(a)
print(b)
c = np.flip(np.argsort(a))
print(c)

[ 6  9 12  3  4  1  2  7  8  0  5 10 11]
[11 10  5  0  8  7  2  1  4  3 12  9  6]


In [151]:

a = np.array([1, 2, 7, 4, 5])
b = np.arange(len(a))
c = b[np.argsort(a)[::-1]]
print(c)

[2 4 3 1 0]


In [154]:
a = np.array([155,1, 2, 83, 14, 5])
b = np.arange(len(a))
c = b[np.argsort(-a)]
print(c)

[0 3 4 5 2 1]


The np.argsort() function in NumPy returns an array of indices that would sort an input array in ascending order. By placing a negative sign before the array a, we are effectively reversing the order in which the elements of a are sorted. This means that the resulting array c will contain the indices that would sort the array a in descending order.

To illustrate this, let's consider the example you provided:

css
Copy code
a = np.array([1, 2, 83, 14, 5])
b = np.arange(len(a))
c = b[np.argsort(-a)]
Here, -a would be [-1, -2, -83, -14, -5]. Since argsort() sorts the array in ascending order, the resulting array of indices would be [2, 3, 4, 1, 0], which corresponds to the indices of the sorted array a in descending order.

Finally, we use the indices in c to index the original array b, resulting in c containing the sorted indices in descending order based on the values of a.




Marek Jędrychowski
And how does the indexing work here?