(1258702, 100, 2)
(1292542, 100, 2)

In [ ]:
import numpy as np
import scipy
from scipy import stats

array1 = np.random.rand(6, 4, 2)
array2 = np.random.rand(6, 4, 2)

In [ ]:
array1.shape

In [ ]:
dataset = [array1, array2]
print(len(dataset))
print(len(dataset[0]))


In [ ]:
global num_features
num_features = 2

def extract_features(extracted_data, chunk_size = dataset[0].shape[1]):
    freq = 100 # Data frequency of 200HZ
    num_chunks = extracted_data.shape[0]//chunk_size
    num_sensors = extracted_data.shape[2]
    features = np.zeros((num_chunks, num_features*num_sensors))
    
    positive = 0
    negative = 0
    
    
    for i in range(num_chunks):
        chunk = extracted_data[i*chunk_size:(i+1)*chunk_size, :, :]

        fft_sum_list = []
        fft_sum_list_1 = []

        fft_vals = np.fft.fft(chunk[i,])
        print(f'fft_vals {fft_vals}')



        for j in range(num_sensors):                
            fft_vals_1 = np.fft.fft(chunk[j,])
            #print(fft_vals_1)
            fft_sum_1 = np.sum(np.abs(fft_vals_1))/freq

            fft_sum_list_1.append(fft_sum_1)




        positive_count = np.count_nonzero(fft_vals_1 > 0)
        negative_count = np.count_nonzero(fft_vals_1 < 0)
        positive += positive_count
        negative += negative_count
        print("Number of positive values:", positive_count)
        print("Number of negative values:", negative_count)


        fft_sum_list = np.array(fft_sum_list)

        features[i,:] = np.concatenate([fft_sum_list])
        global feature_names
        feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
            'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    print(f'total positive values for position {positive}')
    print(f'total negative values for position {negative}')        
    return features


In [ ]:
chunk_size = 100
array4 = np.random.rand(200, 100, 2)
num_chunks = array4.shape[0]//chunk_size
print(num_chunks)

In [ ]:
for i in range (len(dataset)):
    print(len(dataset[i]))
    for j in range(len(dataset[i])):
        #mean = np.mean(dataset[i][j], axis=(0, 1))
        for k in range(dataset[i].shape[2]):
        #    print(dataset[j][k])
        #    print('\n')
        
        
            mean = np.mean(dataset[i][j])

In [ ]:
print(len(dataset))

In [ ]:
print(dataset[0][0][0])

In [160]:
array5 = np.random.rand(2, 2, 2)
print(array5)
mean_array = np.mean(array5[0], axis=0)
print("mean")
print(mean_array)

[[[0.49082608 0.32714676]
  [0.40190756 0.17331429]]

 [[0.05320489 0.16290769]
  [0.15483338 0.29263004]]]
mean
[0.44636682 0.25023053]


In [161]:
print(mean_array[0])
print(mean_array[1])

0.4463668192720745
0.2502305255798803


In [162]:
array5.shape

(2, 2, 2)

In [178]:
global num_features
num_features = 6
def feature_extraction(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
    
    mean_sensor_1 = mean_array[:,0]
    mean_sensor_2 = mean_array[:,1]
    median_sensor_1 = median_array[:,0]
    median_sensor_2 = median_array[:,1]
    std_sensor_1 = std_array[:,0]
    std_sensor_2 = std_array[:,1]
    min_sensor_1 = min_val_array[:,0]
    min_sensor_2 = min_val_array[:,1]
    max_sensor_1 = max_val_array[:,0]
    max_sensor_2 = max_val_array[:,1]
    sum_sensor_1 = sum_val_array[:,0]
    sum_sensor_2 = sum_val_array[:,1]
    print(mean_sensor_1)
    print(sum_sensor_2)
    
    features = np.zeros((len(data), num_features*2))
    
    for i in range(num_features):
        features[i,:] = np.concatenate([mean_sensor_1, mean_sensor_2, median_sensor_1, median_sensor_2, std_sensor_1, std_sensor_2,\
            min_sensor_1, min_sensor_2, max_sensor_1, max_sensor_2, sum_sensor_1, sum_sensor_2])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    
        
    #print(mean_sensor_2)
    #print(mean_array)

In [164]:
feature_extraction(array5)
np.mean(array5[0], axis=0)

[[0.44636682 0.25023053]
 [0.10401913 0.22776887]]
0.4463668192720745
0.2502305255798803


array([0.44636682, 0.25023053])

In [179]:
feature_extraction(array5)

[0.44636682 0.10401913]
[0.00500461 0.00455538]


In [206]:
array7 = np.random.rand(20, 10, 2)

#fft_vals = np.fft.fft(chunk[i,])
#print(f'fft_vals {fft_vals}')

for i in range(len(array7)):
        fft_vals = np.fft.fft(array7[i])
        print(fft_vals)
        
        positive_count = np.count_nonzero(fft_vals > 0)
        negative_count = np.count_nonzero(fft_vals < 0)
        print(positive_count)
        print(negative_count)
        
        


[[ 8.05975737e-01+0.j -6.69567893e-01+0.j]
 [ 1.89818160e+00+0.j -6.28797235e-02+0.j]
 [ 5.80552931e-01+0.j  1.24435859e-01+0.j]
 [ 3.16789794e-01+0.j -1.35594258e-01+0.j]
 [ 1.29386397e+00+0.j  4.44551563e-01+0.j]
 [ 1.26783398e+00+0.j -3.86335848e-01+0.j]
 [ 5.18508222e-01+0.j -2.46875332e-01+0.j]
 [ 5.91668696e-02+0.j  1.79679956e-03+0.j]
 [ 1.18855999e+00+0.j -6.17464821e-01+0.j]
 [ 8.33414216e-01+0.j  3.96385003e-01+0.j]]
14
6
[[ 1.00491917+0.j -0.72081333+0.j]
 [ 1.03725059+0.j -0.35377219+0.j]
 [ 1.59945925+0.j -0.04354942+0.j]
 [ 0.69158299+0.j -0.18424637+0.j]
 [ 0.94338054+0.j  0.40719309+0.j]
 [ 0.50199375+0.j -0.42997151+0.j]
 [ 1.11210146+0.j -0.25296909+0.j]
 [ 1.35479136+0.j -0.40138472+0.j]
 [ 1.47908387+0.j -0.31541318+0.j]
 [ 0.795272  +0.j  0.60994545+0.j]]
12
8
[[ 0.96326183+0.j  0.44149543+0.j]
 [ 1.15194335+0.j -0.66439116+0.j]
 [ 1.16927071+0.j  0.69155881+0.j]
 [ 0.40883756+0.j -0.0030126 +0.j]
 [ 1.02112416+0.j  0.85134332+0.j]
 [ 1.63179202+0.j  0.0247061 +0.j

In [191]:
array8 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
fft_vals = np.fft.fft(array8)
print(fft_vals)

[136. +0.j          -8.+40.21871594j  -8.+19.3137085j   -8.+11.9728461j
  -8. +8.j          -8. +5.3454291j   -8. +3.3137085j   -8. +1.59129894j
  -8. +0.j          -8. -1.59129894j  -8. -3.3137085j   -8. -5.3454291j
  -8. -8.j          -8.-11.9728461j   -8.-19.3137085j   -8.-40.21871594j]


In [205]:
array9 = np.random.rand(10, 10)
print(array9, end = '\n\n')
fft_vals = np.fft.fft(array9)
print(fft_vals, end = '\n\n')

for i in range(len(array9[0])):
    fft_vals2 = np.fft.fft(array9[0])
    
print(fft_vals2, end = '\n\n')

fft_vals3 = np.fft.fft(array9[0])

print(fft_vals3)                      
                       

[[0.99997481 0.28248774 0.30898376 0.51546995 0.61810829 0.92647199
  0.04894968 0.70637222 0.11977002 0.81371487]
 [0.2884913  0.39626661 0.87935844 0.40199579 0.39362724 0.75179054
  0.57569826 0.71704461 0.00782393 0.97725002]
 [0.37902358 0.18580825 0.55416606 0.32025474 0.77682933 0.61349263
  0.88555698 0.92860825 0.26739064 0.94619847]
 [0.78118876 0.62144746 0.84204543 0.67587784 0.45797869 0.57539645
  0.32895248 0.05865526 0.57645894 0.57644728]
 [0.01956231 0.35693688 0.58129605 0.52744931 0.97344297 0.03449377
  0.53564304 0.89222959 0.37017057 0.40941317]
 [0.43006989 0.08394751 0.13766734 0.02765588 0.1456589  0.57039383
  0.34658351 0.49202067 0.82117847 0.27518959]
 [0.19891959 0.55319024 0.45825607 0.93553533 0.67569387 0.36476488
  0.65444269 0.10870999 0.22079024 0.04104458]
 [0.80124714 0.18441184 0.49264375 0.25626866 0.15329229 0.78413999
  0.06393295 0.42728698 0.54058094 0.87331338]
 [0.31081351 0.31378705 0.97894682 0.60862625 0.9567025  0.45773128
  0.58509797

In [203]:
array10 = [[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16]]

print(np.fft.fft(array10[0]))

[55.+0.00000000e+00j -5.+1.53884177e+01j -5.+6.88190960e+00j
 -5.+3.63271264e+00j -5.+1.62459848e+00j -5.-1.33226763e-15j
 -5.-1.62459848e+00j -5.-3.63271264e+00j -5.-6.88190960e+00j
 -5.-1.53884177e+01j]


In [235]:
array11 = np.random.rand(4, 4)
#print(array11, end = '\n\n')
fft_vals = np.fft.fft(array11)
print(fft_vals, end = '\n\n')
#print(fft_vals, end = '\n\n')

positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(positive_count)
print(negative_count)



array12 = np.random.rand(8, 8, 2)
#print(array12)

'''
for i in range(len(array12[0])):
    print(f'Shape of the array: {array12[i].shape}')
    fft_vals = np.fft.fft(array12[0])
    print(fft_vals)
'''
#fft_val = np.fft.fft(array11[0])
#array11 = np.arange(2,2,2)
for i in range(len(array12[0])):
    print(f'Shape of the array: {array12[i].shape}')
    fft_vals = np.fft.fft(array12[0])
    print(fft_vals)


[[ 2.7734347 +0.j         -0.352921  +0.02659327j  0.46973158+0.j
  -0.352921  -0.02659327j]
 [ 2.62358434+0.j          0.64204997-0.0779269j  -0.50230571+0.j
   0.64204997+0.0779269j ]
 [ 2.25836509+0.j          0.03273862+0.06064644j  1.5509066 +0.j
   0.03273862-0.06064644j]
 [ 2.69356037+0.j         -0.54714424+0.06824787j  0.19113158+0.j
  -0.54714424-0.06824787j]]

11
5
Shape of the array: (8, 2)
[[ 0.4042099 +0.j  0.212178  +0.j]
 [ 1.81364674+0.j  0.05221817+0.j]
 [ 1.30265878+0.j  0.02879375+0.j]
 [ 0.18083823+0.j -0.09483376+0.j]
 [ 0.69095552+0.j  0.51474974+0.j]
 [ 0.50005908+0.j -0.05712805+0.j]
 [ 1.36854194+0.j -0.24718469+0.j]
 [ 0.98044778+0.j  0.57144034+0.j]]
Shape of the array: (8, 2)
[[ 0.4042099 +0.j  0.212178  +0.j]
 [ 1.81364674+0.j  0.05221817+0.j]
 [ 1.30265878+0.j  0.02879375+0.j]
 [ 0.18083823+0.j -0.09483376+0.j]
 [ 0.69095552+0.j  0.51474974+0.j]
 [ 0.50005908+0.j -0.05712805+0.j]
 [ 1.36854194+0.j -0.24718469+0.j]
 [ 0.98044778+0.j  0.57144034+0.j]]
Shape

In [233]:
array13 = np.random.rand(1000)

fft_vals = np.fft.fft(array13)
print(fft_vals)



positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(positive_count)
print(negative_count)

[ 4.93720590e+02 +0.j         -1.74780107e+00 +3.5343434j
 -5.45437327e+00 +1.02653018j -8.37356076e-01 -1.60745685j
 -3.12363375e+00-11.40654629j -4.47374086e+00 +0.81372818j
  8.26445176e+00 -0.75691682j  5.36778154e+00 +0.23551128j
 -2.90912638e+00 +5.91884003j -6.90625627e+00 -4.62807027j
  7.71592523e-01 -1.26061416j  4.11818886e+00 +1.13104239j
  6.74496180e+00 +2.05803132j  6.62504184e-01 +2.47146991j
 -9.08156694e-01 -2.58617905j  9.25602942e+00 +8.27126232j
 -3.22569751e+00+10.77940727j -7.08804674e+00 -3.29380877j
  3.71874443e+00 +2.13630816j -1.14711135e+00+14.55545578j
  1.46811002e+01 +1.27506771j  7.71032910e+00 -0.80809602j
 -2.96974813e+00 -8.54363775j -6.54515334e+00 -5.94209469j
  2.05581502e+00 -2.58054768j -2.83508430e+00 -0.53230463j
 -3.71846342e+00 +4.80769733j  2.07293936e-01 -0.96686894j
 -4.51927333e+00 +8.7089278j   2.92266296e+00 -1.01943525j
  2.49630375e+00 -4.97579771j -2.52029228e-01 +5.33551334j
 -1.45377478e+00 -4.46013144j  4.11356016e+00+11.58235571

In [249]:
array14 = np.random.rand(8,8,8)

for i in range(len(array14[0])):
    for j in range(len(array14[1])):
        fft_vals = np.fft.fft(array14)
        
print(fft_vals[0][0], end = '\n\n')
positive_count = np.count_nonzero(fft_vals > 0)
negative_count = np.count_nonzero(fft_vals < 0)
print(f'number of positive fft values: {positive_count}')
print(f'number of negative fft values: {negative_count}', end = '\n\n')

print(fft_vals[0], end = '\n\n\n')




[ 4.07262832+0.j          0.26290559-0.98585429j -0.523807  -0.21876446j
  0.61029147+0.57441598j -0.66985004+0.j          0.61029147-0.57441598j
 -0.523807  +0.21876446j  0.26290559+0.98585429j]

number of positive fft values: 287
number of negative fft values: 225

[[ 4.07262832+0.j          0.26290559-0.98585429j -0.523807  -0.21876446j
   0.61029147+0.57441598j -0.66985004+0.j          0.61029147-0.57441598j
  -0.523807  +0.21876446j  0.26290559+0.98585429j]
 [ 3.99980929+0.j          0.05234711+0.19167736j -0.70876817+0.6987382j
   0.57397348-0.3408477j  -0.06819535+0.j          0.57397348+0.3408477j
  -0.70876817-0.6987382j   0.05234711-0.19167736j]
 [ 3.20851913+0.j          0.63995669-0.50978927j  0.65064959+0.86113674j
   0.27060444-0.51024907j -0.51807438+0.j          0.27060444+0.51024907j
   0.65064959-0.86113674j  0.63995669+0.50978927j]
 [ 4.22492852+0.j          0.10875143-0.48262858j -0.39832151+0.69373605j
   0.52147826+0.38910246j -0.27894934+0.j          0.52147826-0

In [246]:
for i in range(len(array14[0])):
    for j in range(len(array14[1])):
        for k in range(len(array14[2])):
            fft_vals = np.fft.fft(array14)
            

print(fft_vals[0][0][0])

(4.690456225999352+0j)
