(1258702, 100, 2)
(1292542, 100, 2)

In [ ]:
import numpy as np
import scipy
from scipy import stats

array1 = np.random.rand(6, 4, 2)
array2 = np.random.rand(6, 4, 2)

In [ ]:
array1.shape

In [ ]:
dataset = [array1, array2]
print(len(dataset))
print(len(dataset[0]))


In [ ]:
global num_features
num_features = 2

def extract_features(extracted_data, chunk_size = dataset[0].shape[1]):
    freq = 100 # Data frequency of 200HZ
    num_chunks = extracted_data.shape[0]//chunk_size
    num_sensors = extracted_data.shape[2]
    features = np.zeros((num_chunks, num_features*num_sensors))
    
    positive = 0
    negative = 0
    
    
    for i in range(num_chunks):
        chunk = extracted_data[i*chunk_size:(i+1)*chunk_size, :, :]

        fft_sum_list = []
        fft_sum_list_1 = []

        fft_vals = np.fft.fft(chunk[i,])
        print(f'fft_vals {fft_vals}')



        for j in range(num_sensors):                
            fft_vals_1 = np.fft.fft(chunk[j,])
            #print(fft_vals_1)
            fft_sum_1 = np.sum(np.abs(fft_vals_1))/freq

            fft_sum_list_1.append(fft_sum_1)




        positive_count = np.count_nonzero(fft_vals_1 > 0)
        negative_count = np.count_nonzero(fft_vals_1 < 0)
        positive += positive_count
        negative += negative_count
        print("Number of positive values:", positive_count)
        print("Number of negative values:", negative_count)


        fft_sum_list = np.array(fft_sum_list)

        features[i,:] = np.concatenate([fft_sum_list])
        global feature_names
        feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
            'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    print(f'total positive values for position {positive}')
    print(f'total negative values for position {negative}')        
    return features


In [ ]:
chunk_size = 100
array4 = np.random.rand(200, 100, 2)
num_chunks = array4.shape[0]//chunk_size
print(num_chunks)

In [ ]:
for i in range (len(dataset)):
    print(len(dataset[i]))
    for j in range(len(dataset[i])):
        #mean = np.mean(dataset[i][j], axis=(0, 1))
        for k in range(dataset[i].shape[2]):
        #    print(dataset[j][k])
        #    print('\n')
        
        
            mean = np.mean(dataset[i][j])

In [ ]:
print(len(dataset))

In [ ]:
print(dataset[0][0][0])

In [160]:
array5 = np.random.rand(2, 2, 2)
print(array5)
mean_array = np.mean(array5[0], axis=0)
print("mean")
print(mean_array)

[[[0.49082608 0.32714676]
  [0.40190756 0.17331429]]

 [[0.05320489 0.16290769]
  [0.15483338 0.29263004]]]
mean
[0.44636682 0.25023053]


In [161]:
print(mean_array[0])
print(mean_array[1])

0.4463668192720745
0.2502305255798803


In [162]:
array5.shape

(2, 2, 2)

In [178]:
global num_features
num_features = 6
def feature_extraction(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
    
    mean_sensor_1 = mean_array[:,0]
    mean_sensor_2 = mean_array[:,1]
    median_sensor_1 = median_array[:,0]
    median_sensor_2 = median_array[:,1]
    std_sensor_1 = std_array[:,0]
    std_sensor_2 = std_array[:,1]
    min_sensor_1 = min_val_array[:,0]
    min_sensor_2 = min_val_array[:,1]
    max_sensor_1 = max_val_array[:,0]
    max_sensor_2 = max_val_array[:,1]
    sum_sensor_1 = sum_val_array[:,0]
    sum_sensor_2 = sum_val_array[:,1]
    print(mean_sensor_1)
    print(sum_sensor_2)
    
    features = np.zeros((len(data), num_features*2))
    
    for i in range(num_features):
        features[i,:] = np.concatenate([mean_sensor_1, mean_sensor_2, median_sensor_1, median_sensor_2, std_sensor_1, std_sensor_2,\
            min_sensor_1, min_sensor_2, max_sensor_1, max_sensor_2, sum_sensor_1, sum_sensor_2])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    
        
    #print(mean_sensor_2)
    #print(mean_array)

In [164]:
feature_extraction(array5)
np.mean(array5[0], axis=0)

[[0.44636682 0.25023053]
 [0.10401913 0.22776887]]
0.4463668192720745
0.2502305255798803


array([0.44636682, 0.25023053])

In [179]:
feature_extraction(array5)

[0.44636682 0.10401913]
[0.00500461 0.00455538]


In [ ]:
fft_vals = np.fft.fft(chunk[i,])
        print(f'fft_vals {fft_vals}')