In [ ]:
import numpy as np
import scipy
from scipy import stats

In [ ]:
global num_features
num_features = 12
def feature_extraction(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    kurtosis_array = np.empty((len(data),2), dtype = float)
    skewness_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
        kurtosis_array[i] = scipy.stats.kurtosis(data[i], axis=0)
        skewness_array[i] = scipy.stats.skew(data[i], axis=0)
        
    print(mean_array.shape)
    #features = np.zeros((len(data), num_features))
    #print(features.shape)
    #for i in range(num_features):
    #    features[i,:] = np.concatenate([mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    features = np.concatenate((mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array, kurtosis_array, skewness_array), axis = 1)
    return features    
    #print(mean_sensor_2)
    #print(mean_array)

In [4]:
import numpy as np
from scipy.integrate import trapz
from scipy.fft import fft

arr3 = np.random.rand(7,6,2)
mean_array = np.empty((len(arr3),2), dtype = float)
fft_vals = np.empty((len(arr3),2), dtype = float)
fft_sums = np.empty((len(arr3),2), dtype = float)
freq = 100
arr3[0].shape

flat_arr = arr3.reshape(len(arr3)*len(arr3[1]), len(arr3[0][1]))

k = 0
for k in range(len(arr3[1])):
        mean_array[k] = np.mean(arr3[k], axis=0)
        chunk = flat_arr[k * len(arr3[1]) : (k + 1) * len(arr3[1]), ]
        
        sensor_1 = chunk[:,0]
        sensor_2 = chunk[:,1]
        
        
        sp1 = np.fft.fft(np.sin(sensor_1))
        ps1 = np.abs(sp1)**2
        sp2 = np.fft.fft(np.sin(sensor_2))
        ps2 = np.abs(sp2)**2
         
                # Define the frequency range of interest
        sensor_1_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx1 = np.logical_and(sensor_1_freq >= 0, sensor_1_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area1 = trapz(ps1[idx1], sensor_1_freq[idx1])


        # Define the frequency range of interest
        sensor_2_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx2 = np.logical_and(sensor_2_freq >= 0, sensor_2_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area2 = trapz(ps2[idx1], sensor_2_freq[idx1])


        fft_sums[k] = [area1, area2]

        print(f"Area under the curve: {area1:.2f}")
        print(f"Area under the curve: {area2:.2f}")
        
        
        max_ps1 = np.max(sp1)
        max_ps2 = np.max(sp2)
        
            
        argmax_ind_1 = np.arange(len(sp1))

        argmax_list_1 = argmax_ind_1[np.argsort(-np.abs(sp1))]
        
        #for x in argmax_list:
        #        if x * freq
        max_power_frequency_1 = argmax_list_1[0] * (freq / len(chunk))
        
        
        
        argmax_ind_2 = np.arange(len(sp2))
        print(argmax_ind_2)
        argmax_list_2 = argmax_ind_2[np.argsort(-np.abs(sp2))]
        
        
        print('wartosc argmax')
        print(argmax_list_2)
        
        #for x in argmax_list:
        #        if x * freq
        max_power_frequency_2 = argmax_list_2[0] * (freq / len(chunk))
        
        
        
        
        print(len(chunk))
                
print('wartosc argmax')
print(argmax_list_2)
        
#print(mean_array)

#print('\n'*3)

print(fft_sums)
#print(fft_vals)
print(mean_array)

Area under the curve: 57.81
Area under the curve: 158.71
[0 1 2 3 4 5]
wartosc argmax
[0 1 5 2 4 3]
6
Area under the curve: 59.24
Area under the curve: 102.19
[0 1 2 3 4 5]
wartosc argmax
[0 2 4 1 5 3]
6
Area under the curve: 77.65
Area under the curve: 90.13
[0 1 2 3 4 5]
wartosc argmax
[0 1 5 2 4 3]
6
Area under the curve: 58.91
Area under the curve: 71.29
[0 1 2 3 4 5]
wartosc argmax
[0 5 1 2 4 3]
6
Area under the curve: 60.07
Area under the curve: 79.99
[0 1 2 3 4 5]
wartosc argmax
[0 2 4 1 5 3]
6
Area under the curve: 32.02
Area under the curve: 82.80
[0 1 2 3 4 5]
wartosc argmax
[0 1 5 2 4 3]
6
wartosc argmax
[0 1 5 2 4 3]
[[ 57.80981558 158.70643512]
 [ 59.23634934 102.19004997]
 [ 77.65172329  90.12664931]
 [ 58.90829468  71.29062256]
 [ 60.06995958  79.99478386]
 [ 32.02194695  82.79901464]
 [  0.           0.        ]]
[[4.54103132e-001 8.16004158e-001]
 [4.48989749e-001 6.02946059e-001]
 [5.08407673e-001 5.67058134e-001]
 [4.24832460e-001 4.56080032e-001]
 [4.34193809e-001 5