In [ ]:
import os
import numpy as np
data_dir = './CreatedFiles/Extracted_Features/'
label_dir = './CreatedFiles/Labels/'


def file_merging(num_features, num_sensors):
    n = num_features * 2
    
    X = np.zeros((1, n, num_sensors))
    y = np.empty((1, 1))
    for filename in os.listdir(data_dir):
        file_loaded = np.load(data_dir + filename)
        #print(file_loaded.shape)
        #X = np.concatenate(file_loaded)
        #print(X)
        #print(sum(sum(np.isnan(file_loaded))))
        print(filename)
        print(file_loaded)
        print(filename)
    '''
        if sum(sum(np.isnan(file_loaded))) > 0:
            print(filename)
            print(file_loaded.shape)
            print(sum(sum(np.isnan(file_loaded))))
    '''
    '''    
    for label in os.listdir(label_dir):

        label_loaded = np.load(label_dir + label)
    return X,y
    
    '''

In [ ]:
z = file_merging(10,2)[0]

In [ ]:
print(z)

In [ ]:
import os
import numpy as np
segment = './CreatedFiles/Segmentation/'
label_dir = './CreatedFiles/Labels/'


for filename in os.listdir(segment):
    load_file = np.load(segment + filename)
    #print(load_file)
    
    for row in load_file:
    
        if sum(sum(np.isnan(row))) > 0:
                print(filename)
                print(load_file.shape)
                print(sum(sum(np.isnan(load_file))))
            


In [ ]:
import os
import numpy as np
segment = './CreatedFiles/Segmentation/'
label_dir = './CreatedFiles/Labels/'


for filename in os.listdir(segment):
    load_file = np.load(segment + filename)
    print(filename)
    #print(load_file)
    print(sum(sum(sum(np.isnan(load_file)))))
    
    '''
    for i in range(len(load_file)):
            print(filename)
            print(sum(sum(sum(np.isnan(load_file)))))
            print(load_file.shape)
            #print(sum(sum(np.isnan(load_file))))
            #print(sum(sum(np.isnan(load_file))))
    '''        

In [ ]:
R5 = np.load('./CreatedFiles/Segmentation/5_R.npy')
print(R5.shape)

In [ ]:
import os
import numpy as np
data_dir = './CreatedFiles/Extracted_Features/'
label_dir = './CreatedFiles/Labels/'

num_features = 10
num_sensors = 2

n = num_features * 2

X = np.zeros((1, n, num_sensors))
y = np.empty((1, 1))
for filename in os.listdir(data_dir):

    file_loaded = np.load(data_dir + filename)

    print(filename)
    print(file_loaded)
    print(filename)



In [186]:
import os
import numpy as np
import re
data_dir = './CreatedFiles/Extracted_Features/'
label_dir = './CreatedFiles/Labels/'
target_dir = './CreatedFiles/Entire_Set/'

def file_merging(num_features, num_sensors):

    
    X = np.empty((0, num_features * num_sensors))
    y = np.empty(0)
    
    for filename in os.listdir(data_dir):
        file_loaded = np.load(data_dir + filename)
        print(file_loaded.shape)
        X = np.concatenate((X, file_loaded), axis = 0)
        print(file_loaded.shape)
        print(X)
        print('\n'*3)
        

        if np.isnan(file_loaded).any():
            print(f"Skipping {filename} due to NaN values")
            break

        
        if sum(sum(np.isnan(file_loaded))) > 0:
            print(filename)
            print(file_loaded.shape)
            print(sum(sum(np.isnan(file_loaded))))
            break

    for label in os.listdir(label_dir):
        label_loaded = np.load(label_dir + label)

        y = np.concatenate((y, label_loaded), axis = 0)
    
    Data = f'{target_dir}{X}'
    Labels = f'{target_dir}{y}'
    np.save(Data, X)
    np.save(Labels, y)
#    return X,y


In [187]:
z = file_merging(10,2)

(3926, 20)
(3926, 20)
[[-2.03750134e-02 -1.60930004e+01 -1.52500002e-02 ...  2.70578970e+07
   9.94000000e+01  9.88000000e+01]
 [ 1.40800211e-03 -2.42600012e+00  1.11250002e-02 ...  2.30139152e+07
   9.94000000e+01  1.20000000e+00]
 [ 3.00519932e-02 -1.97549992e+01  4.82500009e-02 ...  2.92110335e+08
   9.94000000e+01  9.98000000e+01]
 ...
 [ 6.14599884e-03  1.61539993e+01  1.46249998e-02 ...  1.93050879e+08
   9.96000000e+01  9.90000000e+01]
 [ 3.36199976e-03 -2.05079994e+01  6.00000005e-03 ...  1.97787647e+08
   9.96000000e+01  9.90000000e+01]
 [-1.90470088e-02 -1.30999994e+00 -3.11249997e-02 ...  2.34631194e+08
   9.90000000e+01  9.90000000e+01]]




(5830, 20)
(5830, 20)
[[-2.03750134e-02 -1.60930004e+01 -1.52500002e-02 ...  2.70578970e+07
   9.94000000e+01  9.88000000e+01]
 [ 1.40800211e-03 -2.42600012e+00  1.11250002e-02 ...  2.30139152e+07
   9.94000000e+01  1.20000000e+00]
 [ 3.00519932e-02 -1.97549992e+01  4.82500009e-02 ...  2.92110335e+08
   9.94000000e+01  9.98000000e+01]
 

In [153]:
print(z)

[[-2.03750134e-02 -1.60930004e+01 -1.52500002e-02 ...  2.70578970e+07
   9.94000000e+01  9.88000000e+01]
 [ 1.40800211e-03 -2.42600012e+00  1.11250002e-02 ...  2.30139152e+07
   9.94000000e+01  1.20000000e+00]
 [ 3.00519932e-02 -1.97549992e+01  4.82500009e-02 ...  2.92110335e+08
   9.94000000e+01  9.98000000e+01]
 ...
 [-2.55601811e+00 -1.68000000e+02 -2.55599999e+00 ...  7.05600000e+08
   6.82000000e+01  4.00000000e+01]
 [-2.55601811e+00 -1.68000000e+02 -2.55599999e+00 ...  7.05600000e+08
   6.82000000e+01  4.00000000e+01]
 [-2.55601811e+00 -1.68000000e+02 -2.55599999e+00 ...  7.05600000e+08
   6.82000000e+01  4.00000000e+01]]


In [154]:
z.shape

(510160, 20)

In [113]:
zarr = np.random.rand(2,3,4)
garr = np.random.rand(2,3,4)

In [114]:
print(zarr)
print('\n'*4)
print(garr)

[[[0.52107766 0.49101247 0.26723927 0.053954  ]
  [0.92181165 0.81141108 0.68044806 0.398352  ]
  [0.57247957 0.36733392 0.89335067 0.1474021 ]]

 [[0.77383172 0.43869761 0.87397555 0.34613465]
  [0.82579934 0.61283637 0.91723975 0.28789544]
  [0.79891249 0.70602972 0.65236888 0.29928523]]]





[[[0.16726519 0.40443014 0.58744935 0.59069798]
  [0.3942344  0.05132394 0.66754243 0.76749337]
  [0.60497446 0.38027997 0.87822095 0.29405708]]

 [[0.03983108 0.51742203 0.02936437 0.10654557]
  [0.92262484 0.71888947 0.96750194 0.68524244]
  [0.9896227  0.43961375 0.2072117  0.78100713]]]


In [115]:
garr = np.concatenate((zarr,garr), axis = 0)
print(garr)

[[[0.52107766 0.49101247 0.26723927 0.053954   0.16726519 0.40443014
   0.58744935 0.59069798]
  [0.92181165 0.81141108 0.68044806 0.398352   0.3942344  0.05132394
   0.66754243 0.76749337]
  [0.57247957 0.36733392 0.89335067 0.1474021  0.60497446 0.38027997
   0.87822095 0.29405708]]

 [[0.77383172 0.43869761 0.87397555 0.34613465 0.03983108 0.51742203
   0.02936437 0.10654557]
  [0.82579934 0.61283637 0.91723975 0.28789544 0.92262484 0.71888947
   0.96750194 0.68524244]
  [0.79891249 0.70602972 0.65236888 0.29928523 0.9896227  0.43961375
   0.2072117  0.78100713]]]


In [116]:
garr.shape

(2, 3, 8)

In [146]:
X = np.empty((0, num_features * num_sensors))
print(X)

[]


In [148]:
y = np.empty((0, 1))
print(y)

[]
