In [22]:
import numpy as np
import scipy
from scipy import stats
from scipy.integrate import trapz
from scipy.fft import fft

In [23]:
global num_features
num_features = 12
def feature_extraction2(data):
    freq = 100
    mean_array = np.empty((len(data),2), dtype = float)
    median_array = np.empty((len(data),2), dtype = float)
    std_array = np.empty((len(data),2), dtype = float)
    min_val_array = np.empty((len(data),2), dtype = float)
    max_val_array = np.empty((len(data),2), dtype = float)
    sum_val_array = np.empty((len(data),2), dtype = float)
    kurtosis_array = np.empty((len(data),2), dtype = float)
    skewness_array = np.empty((len(data),2), dtype = float)
    for i in range(len(data)):
        mean_array[i] = np.mean(data[i], axis=0)
        median_array[i] = np.median(data[i], axis=0)
        std_array[i] = np.std(data[i], axis=0)
        min_val_array[i] = np.min(data[i], axis=0)
        max_val_array[i] = np.max(data[i], axis=0)
        sum_val_array[i] = np.sum(data[i], axis=0)/freq
        
        kurtosis_array[i] = scipy.stats.kurtosis(data[i], axis=0)
        skewness_array[i] = scipy.stats.skew(data[i], axis=0)
        
    print(mean_array.shape)
    #features = np.zeros((len(data), num_features))
    #print(features.shape)
    #for i in range(num_features):
    #    features[i,:] = np.concatenate([mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array])
        
    global feature_names
    feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
        'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
    
    features = np.concatenate((mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array, kurtosis_array, skewness_array), axis = 1)
    return features    
    #print(mean_sensor_2)
    #print(mean_array)

In [24]:
import numpy as np
from scipy.integrate import trapz
from scipy.fft import fft

data = np.random.rand(8,6,2)
fft_vals = np.empty((len(data),2), dtype = float)
fft_sums = np.empty((len(data),2), dtype = float)
fft_freqs = np.empty((len(data),2), dtype = float)
freq = 100
#Flattening the array to shape (a*b, c), where c is the number of sensors
flat_arr = data.reshape(len(data)*len(data[1]), len(data[0][1]))


k = 0
for k in range(len(data)):
        
        chunk = flat_arr[k * len(data[1]) : (k + 1) * len(data[1]), ]
        
        sensor_1 = chunk[:,0]
        sensor_2 = chunk[:,1]
        
        
        sp1 = np.fft.fft(np.sin(sensor_1))
        ps1 = np.abs(sp1)**2
        sp2 = np.fft.fft(np.sin(sensor_2))
        ps2 = np.abs(sp2)**2
        
        
        # Define the frequency range of interest
        sensor_1_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx1 = np.logical_and(sensor_1_freq >= 0, sensor_1_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area1 = trapz(ps1[idx1], sensor_1_freq[idx1])


        # Define the frequency range of interest
        sensor_2_freq = np.fft.fftfreq(len(chunk), 1/freq)
        
        idx2 = np.logical_and(sensor_2_freq >= 0, sensor_2_freq <= freq)

        # Integrate the power spectrum over the frequency range of interest
        area2 = trapz(ps2[idx1], sensor_2_freq[idx1])


        fft_sums[k] = [area1, area2]
        
            
        argmax_ind_1 = np.arange(len(sp1))
        argmax_list_1 = argmax_ind_1[np.argsort(-np.abs(sp1))]
        
        max_power_frequency_1 = argmax_list_1[0] * (freq / len(chunk))
        
        
        argmax_ind_2 = np.arange(len(sp2))
        argmax_list_2 = argmax_ind_2[np.argsort(-np.abs(sp2))]
        

        
        print(argmax_list_1)
        print(argmax_list_2)

        
        array_len_1 = len(argmax_list_1)
        
        
        for ind_1 in range(array_len_1):
                
                if (argmax_list_1[ind_1] * (freq / len(chunk)) <= 1):
                        continue
                elif (argmax_list_1[ind_1] * (freq / len(chunk)) > 1):
                        max_power_frequency_1 = argmax_list_1[ind_1] * (freq / len(chunk))
                        print(f'Max power frequency for array 1 %.2f' % max_power_frequency_1)
                        print(argmax_list_1[ind_1])
      
                        break

                print(ind_1)
                print(argmax_list_1[ind_1])

        array_len_2 = len(argmax_list_2)

        for ind_2 in range(array_len_2):
                
                if (argmax_list_2[ind_2] * (freq / len(chunk)) <= 1):
                        continue
                elif (argmax_list_2[ind_2] * (freq / len(chunk)) > 1):
                        max_power_frequency_2 = argmax_list_2[ind_2] * (freq / len(chunk))
                        print(f'Max power frequency for array 2 %.2f' % max_power_frequency_2)
                        print(argmax_list_2[ind_2])
      
                        break

                print(ind_1)
                print(argmax_list_1[ind_1])             

             

        
        
        


[0 3 2 4 1 5]
[0 2 4 5 1 3]
Max power frequency for array 1 50.00
3
Max power frequency for array 2 33.33
2
[0 2 4 1 5 3]
[0 3 1 5 2 4]
Max power frequency for array 1 33.33
2
Max power frequency for array 2 50.00
3
[0 3 1 5 2 4]
[0 2 4 3 1 5]
Max power frequency for array 1 50.00
3
Max power frequency for array 2 33.33
2
[0 1 5 2 4 3]
[0 3 2 4 1 5]
Max power frequency for array 1 16.67
1
Max power frequency for array 2 50.00
3
[0 1 5 2 4 3]
[0 1 5 2 4 3]
Max power frequency for array 1 16.67
1
Max power frequency for array 2 16.67
1
[0 3 2 4 1 5]
[0 2 4 3 1 5]
Max power frequency for array 1 50.00
3
Max power frequency for array 2 33.33
2
[0 1 5 2 4 3]
[0 2 4 3 5 1]
Max power frequency for array 1 16.67
1
Max power frequency for array 2 33.33
2
[0 2 4 3 1 5]
[0 2 4 1 5 3]
Max power frequency for array 1 33.33
2
Max power frequency for array 2 33.33
2


In [69]:
import numpy as np
import scipy
from scipy import stats
from scipy.integrate import trapz
from scipy.fft import fft

global num_features
num_features = 10
def feature_extraction(data):
        freq = 100
        mean_array = np.empty((len(data),2), dtype = float)
        median_array = np.empty((len(data),2), dtype = float)
        std_array = np.empty((len(data),2), dtype = float)
        min_val_array = np.empty((len(data),2), dtype = float)
        max_val_array = np.empty((len(data),2), dtype = float)
        sum_val_array = np.empty((len(data),2), dtype = float)
        kurtosis_array = np.empty((len(data),2), dtype = float)
        skewness_array = np.empty((len(data),2), dtype = float)
        for i in range(len(data)):
                mean_array[i] = np.mean(data[i], axis=0)
                median_array[i] = np.median(data[i], axis=0)
                std_array[i] = np.std(data[i], axis=0)
                min_val_array[i] = np.min(data[i], axis=0)
                max_val_array[i] = np.max(data[i], axis=0)
                sum_val_array[i] = np.sum(data[i], axis=0)/freq
                
                kurtosis_array[i] = scipy.stats.kurtosis(data[i], axis=0)
                skewness_array[i] = scipy.stats.skew(data[i], axis=0)


        fft_sums = np.zeros((len(data),2), dtype = float)

        fft_freqs = np.zeros((len(data),2), dtype = float)

        #Flattening the array to shape (a*b, c), where c is the number of sensors
        flat_arr = data.reshape(len(data)*len(data[1]), len(data[0][1]))

        
        k = 0
        for k in range(len(data)):
                
                chunk = flat_arr[k * len(data[1]) : (k + 1) * len(data[1]), ]
                
                sensor_1 = chunk[:,0]
                sensor_2 = chunk[:,1]
                
                
                sp1 = np.fft.fft(np.sin(sensor_1))
                ps1 = np.abs(sp1)**2
                sp2 = np.fft.fft(np.sin(sensor_2))
                ps2 = np.abs(sp2)**2
                
                
                # Define the frequency range of interest
                sensor_1_freq = np.fft.fftfreq(len(chunk), 1/freq)
                
                idx1 = np.logical_and(sensor_1_freq >= 0, sensor_1_freq <= freq)

                # Integrate the power spectrum over the frequency range of interest
                area1 = trapz(ps1[idx1], sensor_1_freq[idx1])


                # Define the frequency range of interest
                sensor_2_freq = np.fft.fftfreq(len(chunk), 1/freq)
                
                idx2 = np.logical_and(sensor_2_freq >= 0, sensor_2_freq <= freq)

                # Integrate the power spectrum over the frequency range of interest
                area2 = trapz(ps2[idx1], sensor_2_freq[idx1])


                fft_sums[k] = [area1, area2]
                
                
                argmax_ind_1 = np.arange(len(sp1))
                argmax_list_1 = argmax_ind_1[np.argsort(-np.abs(sp1))]
                
                max_power_frequency_1 = argmax_list_1[0] * (freq / len(chunk))
                
                
                argmax_ind_2 = np.arange(len(sp2))
                argmax_list_2 = argmax_ind_2[np.argsort(-np.abs(sp2))]
                
                
                array_len_1 = len(argmax_list_1)
                
                for ind_1 in range(array_len_1):
                        
                        if (argmax_list_1[ind_1] * (freq / len(chunk)) <= 1):
                                
                                continue
                        
                        elif (argmax_list_1[ind_1] * (freq / len(chunk)) > 1):
                                max_power_frequency_1 = argmax_list_1[ind_1] * (freq / len(chunk))

                                break
                        
                array_len_2 = len(argmax_list_2)

                for ind_2 in range(array_len_2):
                        
                        if (argmax_list_2[ind_2] * (freq / len(chunk)) <= 1):
                                
                                continue
                        
                        elif (argmax_list_2[ind_2] * (freq / len(chunk)) > 1):
                                max_power_frequency_2 = argmax_list_2[ind_2] * (freq / len(chunk))
        
                                break
           
        
        
                fft_freqs[k] = [max_power_frequency_1, max_power_frequency_2]


        global feature_names
        feature_names = ['mean', 'mean_2', 'median', 'median_2', 'std', 'std_2', 'min_val', 'min_val_2',\
                'max_val', 'max_val_2', 'sum_val', 'sum_val_2', 'kurtosis', 'kurtosis_2', 'skew', 'skew_2', 'fft_sum', 'fft_sum_2']
        
        features = np.zeros((len(data), num_features))        

        features = np.concatenate((mean_array, median_array, std_array, min_val_array, max_val_array, sum_val_array, kurtosis_array, skewness_array, fft_sums, features), axis = 1)
        return features    


In [70]:
arr3 = np.random.rand(8,6,2)
x = feature_extraction(arr3)
#print(x)

(8, 2)
fft sums
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
fft sums
[0 2 4 3 1 5]
[0 3 1 5 2 4]
Max power frequency for array 1 33.33
2
Max power frequency for array 2 50.00
3
fft_freqs
[[33.33333333 50.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[0 5 1 3 2 4]
[0 3 2 4 5 1]
Max power frequency for array 1 83.33
5
Max power frequency for array 2 50.00
3
fft_freqs
[[33.33333333 50.        ]
 [83.33333333 50.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[0 2 4 1 5 3]
[0 2 4 3 1 5]
Max power frequency for array 1 33.33
2
Max power frequency for array 2 33.33
2
fft_freqs
[[33.33333333 50.        ]
 [83.33333333 50.        ]
 [33.33333333 33.33333333]
 [ 0.          0.        ]
 [ 0. 